name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and Test with Gradle
        run: |
          ./gradlew clean test jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
